# Generated by Django 5.2.8 on 2025-11-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование товара: "Картина"', max_length=100, unique=True, verbose_name='Название')),
                ('description', models.CharField(help_text='Описание товара', max_length=200, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Порядок отображения (меньше - выше)', max_digits=10, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товар',
                'ordering': ['name'],
            },
        ),
    ]
